travis:
  secure:
    BINSTAR_TOKEN: q1fQVzVqJbagCOhU6AwkqpS7A8Ll05LcdEboLgKoZ5ZcOwr4YT98Kpwj5uphK8qS8X48S1WXxXfrIGjJ8PoK3UUBJeVPRgZSLko0+y1Cj1ZB41vIkT25wFRsAUWvfLYzSBwoHn7p4JXspvkOMquDRZn27wnX6PiXLcIaKq2Eb8tKNL3ws+sQoLCwYnHoDZnjD0rQ1pxRO4jzR7xp5Tg9kCC9oUVB2UzE20dbN4mRTg7zIAjB5JWhkPSrxO6MxGv5iN+TLYdey6RnD2L3mVrMO7R9QZKS+D3cA4apiVHKFHids0eHUrTVwyWo+hkQGoDPh35KgSBUNKdiRzor64SGFg0Sa7whsm48pj3sEG0lAZ+jQ16hneGcXHrw4G3ybAWehhywQ95Yboa6xnHCrxcftYToX2E7XI4bYuiahNS8elcOLEMQKPwqVIMgPBKXEHVbFzexwaEyox0q7keGgs5nklfSvd/CZKNn+HJLZ79Jeg8HZc8Mp9ftJ7LMPMuJATeEkmgLcwmHIVueAwAdnA/ERye7vT9R1BW+WxyiLkgU6BuiQ3q2jW13f4mt0qsW0BT+YYm+x/rLthpe73zgdRu7UsfoQWL7HE/Ql8XCpgxPP8jMCDST4vNQSIgLvyUUJhJfxaeNEWzmyXw6hRX/SvDkbanOx5CZCG7kg0kh/lV/tuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
