travis:
  secure:
    BINSTAR_TOKEN: m43xDnKhNan6zDX59XlEikPVHfofpVmGgSr4s+ZkG9UHzrOaMfkzbyQCimX3oWs2ozjRxip84301EholLbm19IjfTd8h0/dKmm9cFYYZo/6L8lmVT0gAIcfdl6Rj2AqnGa2w61hsYUD5XE8oJc6sK9seDsiVkIlKwENqQMZOv/cun3o/pqaxJ4XkjmvLETGe7+tzmS0CNDdPo3hM1ywIrgx12ZQlAzNaRq3dRTymPyBf97dihF+/0Bhp9EuH4VO96fSOaCP8C1+bdzBk5DKUYz3aj9Pa2SZkoRGCPBxgszpcKOfgXfiq/xxaZLWfA81tWP8jd9MG32LTXTAM6spVV4USCQ5WbnzynhABTJ75YmnN2l6RSzvRT3jCVoq3WglcKFJ0t2YNS5driPz76/FMua/VcnflhrRYGIRKDyTWtddCq/7n9HKn9GgAWrUekGG95R9DjjAApwmO8wuFrLqZbbuKZTQgvouIYsSUc2sqMocX0yaVKIP+Xt/mOarLLQorvDNCOxRr4r/QuC0aquVvinFoidh+meYNKKo8DRh3T62aHRfgaIVBNzhBDUy0D0Jd/qsDJR2d57vKiAZYE899aeRQ001pMtkmd45C1JOIwbGvlJv1SnpCJjyFaphW+cDSidsldjZkWVNZtaVsuoHaaKgA9khdO0mLOESPYD/CJ64=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
